### ISSUE TITLE
How would you do :+1: (the thumbs up)?

### ISSUE THREAD

**Issue by michaellee** [IonicaBizau/emojic#4]
I'm trying to do the thumbs up emoji, which on the reference site says it is `:+1:` but don't think I should be calling `emojic.+1`. Wondering how to use the thumbsup emoji?

**Comment by IonicaBizau** [comment]
It was not possible before, it's possible now. 😁 

Use `emojic.thumbsUp`.

**Comment by michaellee** [comment]
Awesome thanks @IonicaBizau! Really digging the package. Using it in a command-line tool I'm writing 😄

**Comment by IonicaBizau** [comment]
Great! ✨
